site_name: Application Properties
# site_url: http://127.0.0.1:8000/
site_description: TBD
site_author: Jack De Winter
theme: readthedocs
# repo_url: https://github.com/jackdewinter/application_properties
docs_dir: src
site_dir: site
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [..]
          options:
            docstring_style: google
            docstring_section_style: list
            members_order: source
            show_source: false
            group_by_category: false
            show_symbol_type_heading: true
            show_root_heading: true
            show_root_full_path: true
            show_category_heading: false
            relative_crossrefs: true
            signature_crossrefs: false

nav:
  - "Introduction":
    - 'index.md'
    - 'getting-started.md'
    - 'file-types.md'
    - 'command-line.md'
  - "User Guide":
    - 'user-guide.md'
  - "Usual Project Stuff":
    - 'usual.md'
    - 'contribute.md'
    - "Changelog" : changelog.md
    - "Frequently Asked Questions": faq.md
markdown_extensions:
  - toc:
      permalink: "#"
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
theme:
  name: material
  features:
    - content.tabs.link
  navigation_depth: 5
