site_name: Application Properties
# site_url: http://127.0.0.1:8000/
site_description: TBD
site_author: Jack De Winter
theme: readthedocs
# repo_url: https://github.com/jackdewinter/application_properties
docs_dir: src
site_dir: site
plugins:
  - search
  - mermaid2:
      version: 10.0.2
  - mkdocstrings:
      handlers:
        python:
          paths: [..]
          options:
            docstring_style: google
            docstring_section_style: list
            members_order: source
            show_source: false
            group_by_category: false
            show_symbol_type_heading: true
            show_root_heading: true
            show_root_full_path: true
            show_category_heading: false
            relative_crossrefs: true
            signature_crossrefs: false

nav:
  - "Introduction":
    - 'index.md'
    - 'getting-started.md'
  - "Quick Start":
    - 'quick-starts/index.md'
    - 'quick-starts/installation.md'
    - 'quick-starts/loaders.md'
    - 'quick-starts/getters.md'
    - 'quick-starts/validation.md'
    - 'quick-starts/layering.md'
    - 'quick-starts/hierarchy.md'
    - 'quick-starts/manual.md'
    - 'quick-starts/advanced.md'
  - "User Guide":
    - 'user-guide.md'
    - 'basic-concepts.md'
    - 'file-types.md'
    - 'layering.md'
    - 'heavy.md'
    - 'command-line.md'
    - "API Listing": api/application_properties.md
    - 'custom.md'
  - "Usual Project Stuff":
    - 'usual.md'
    - 'contribute.md'
    - "Changelog" : changelog.md
    - "Frequently Asked Questions": faq.md
markdown_extensions:
  - toc:
      permalink: "#"
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
theme:
  name: material
  features:
    - content.tabs.link
  navigation_depth: 5
